#! /bin/sh

#---- conditional display settings ----#
case $(hostnamectl hostname) in
    "bean")
        PRIMARYMON="DisplayPort-0"
        SECONDARYMON="HDMI-A-0"
        (polybar -c ~/.config/polybar/config.ini top) &
        (polybar -c ~/.config/polybar/config.ini dualmonitor) &
    ;;

    "lettuce")
        PRIMARYMON="eDP1"
        SECONDARYMON="HDMI1"
        (polybar -c ~/.config/polybar/config.ini top) &
        (polybar -c ~/.config/polybar/config.ini bottom) &
    ;;
esac
        

if ((xrandr --query | grep -q "${PRIMARYMON} connected") && (xrandr --query | grep -q "${SECONDARYMON} connected")) 
then
    xrandr --output $PRIMARYMON --primary --mode "2560x1080" --right-of $SECONDARYMON --output eDP1 --off
    bspc config -m $PRIMARYMON top_padding		        30
    bspc config -m $SECONDARYMON top_padding        	0
    bspc config -m $PRIMARYMON bottom_padding           30
    bspc config -m $SECONDARYMON bottom_padding        	0
    # Otherwise eDP1 will be discovered. We must do this
    # before bspc monitor -d/--reset-desktops or else we'll get another Desktop
    # from eDP1
    bspc config remove_disabled_monitors  true
    bspc config remove_unplugged_monitors  true
    bspc monitor $PRIMARYMON    -d                 
    bspc monitor $SECONDARYMON  -d                 
    bspc monitor $PRIMARYMON    -a                  
    bspc monitor $SECONDARYMON  -a                  
# if not, then check if at least SECONDARYMON is plugged in
# should only hit this condition on lettuce
elif (xrandr --query | grep -q "${SECONDARYMON} connected")
then
    xrandr --output eDP1 --primary --left-of HDMI1 --output HDMI1 --mode "2560x1080" 
    bspc config -m HDMI1 top_padding        0
    bspc config -m eDP1 top_padding         30
    bspc monitor eDP1 -d 1 2 3
    bspc monitor HDMI1 -d "4 [Monitor]"
# otherwise, i'm just running on the laptop
else
    bspc config top_padding        30
    bspc config bottom_padding     30
    bspc monitor $PRIMARYMON -d 1 2 3 4 5
fi

#---- settings ----#
bspc config automatic_scheme spiral
bspc config border_width            3
bspc config window_gap              5
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config click_to_focus          true
bspc config focus_follows_pointer   false

#---- colors ----#
bspc config focused_border_color \#81A1C1
bspc config normal_border_color \#2E3440

#---- rules ----#

#---- autostart ----#
(sleep 1 && nitrogen --restore) &
(sleep 1 && sxhkd) &
xrdb ~/.Xresources &
compton &
nm-applet &
xfce4-clipman & 
# helps window rendering in some java apps
wmname LG3D

