#! /usr/bin/python2
# coding=UTF-8

import subprocess
from panel_colors import *

percent = float(subprocess.check_output('xbacklight').rstrip())

brightness= int(percent)

if brightness > 90:
    print " ^fg("+PANEL_URGENT+")■■■■■^fg()"
elif brightness > 79:
    print " ^fg("+PANEL_URGENT+")■■■■^fg("+PANEL_FG+")■^fg()"
elif brightness > 59:
    print " ^fg("+PANEL_URGENT+")■■■^fg("+PANEL_FG+")■■^fg()"
elif brightness > 39:
    print " ^fg("+PANEL_URGENT+")■■^fg("+PANEL_FG+")■■■^fg()"
elif brightness > 19:
    print " ^fg("+PANEL_URGENT+")■^fg("+PANEL_FG+")■■■■^fg()"
else:
    print " ^fg("+PANEL_FG+")■■■■■^fg()"

    
