#! /usr/bin/python2

import subprocess
from panel_colors import *
try:
    desktops = subprocess.check_output(['bspc','control', '--get-status'])
    desktops = desktops.split(":")[1:-1]
    output = ""
    for desktop in desktops:
        if 'O' in desktop:
            output += "^fg(" + PANEL_HIGHLIGHT +  ") ^r(5x5)^fg()"
        elif 'o' in desktop: 
            output += "^fg(" + PANEL_URGENT +  ") ^r(5x5)^fg()"
        elif 'F' in desktop: 
            output += "^fg(" + PANEL_HIGHLIGHT +  ") ^ro(5x5)^fg()"
        elif 'f' in desktop: 
            output += "^fg(" + PANEL_FG +  ") ^ro(5x5)^fg()"
        else:
            output += "^fg(" + PANEL_FG   +  ") ^ro(5x5)^fg()"
    print output
except:
    print ""


