#! /usr/bin/python2
# coding=UTF-8

import imaplib

USER='you@example.com'
PASS='yourpassword'

m = imaplib.IMAP4_SSL('imap.gmail.com', '993')
try:
    m.login(USER, PASS)
except:
    print 'Login Failed'

m.select()
num = len(m.search(None, 'UnSeen')[1][0].split())

if num==0:
    print '', num
else:
   print '', num

m.logout()
