#! /usr/bin/python2
# code=UTF-8

import subprocess
try:
    percent = subprocess.check_output(['iwconfig','wlp3s0'])
    if 'ESSID' in percent:
        percent = percent.split('\"')
        if len(percent[1]) <= 8:
            print percent[1]
        else:
            print percent[1][:8] 
    else:
        print "down"
except:
    print "down"


