#! /bin/sh

bspc config border_width        3
bspc config window_gap         15
bspc config top_padding        30
bspc config bottom_padding     30

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config click_to_focus      true

#---- colors ----#
bspc config focused_border_color \#FF081F
bspc config normal_border_color \#22313c

bspc monitor eDP1 -d I II III IV V


#---- rules ----#
#bspc rule -a Gimp desktop=^8 follow=on floating=on

#---- autostart ----#
(sleep 1 && nitrogen --restore) &
sxhkd &
xrdb ~/.Xresources &
compton &
(sleep 3 && ~/git-repos/polybar/build/bin/polybar bottom) &
(sleep 3 && ~/git-repos/polybar/build/bin/polybar top) &
nm-applet &
wmname LG3D
