#! /bin/sh

bspc config border_width        2
bspc config window_gap         10
bspc config top_padding        30

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#---- colors ----#
bspc config focused_border_color #A0A0A0
bspc config normal_border_color #202020
bspc config urgent_border_color #FFA200


bspc monitor -d I II III IV V


#---- rules ----#
#bspc rule -a Gimp desktop=^8 follow=on floating=on

#---- autostart ----#
(sleep 3 && ~/.config/bspwm/panel/panel_dzen) &
(sleep 1 && nitrogen --restore) &
~/.config/bspwm/panel/scripts/updater &
~/.config/bspwm/panel/bottombar &
compton --config ~/.config/.compton.conf &
pulseaudio &
