#! /bin/sh

#---- conditional display settings ----#
# if both external monitors are plugged in
if ((xrandr --query | grep -q "HDMI1 connected") && (xrandr --query | grep -q "DP2 connected")) 
then
    xrandr --output HDMI1 --primary --mode "2560x1080" --right-of DP2 --output eDP1 --off
    bspc config -m HDMI1 top_padding      30
    bspc config -m DP2 top_padding        0
    # Otherwise eDP1 will be discovered. We must do this
    # before bspc monitor -d/--reset-desktops or else we'll get another Desktop
    # from eDP1
    bspc config remove_disabled_monitors  true
    bspc config remove_unplugged_monitors  true
    bspc monitor DP2 -d                   1 2
    bspc monitor HDMI1 -d                 3 4
# if not, then check if at least hdmi is plugged in
elif (xrandr --query | grep -q "HDMI1 connected")
then
    xrandr --output eDP1 --primary --left-of HDMI1 --output HDMI1 --mode "2560x1080" 
    bspc config -m HDMI1 top_padding        0
    bspc config -m eDP1 top_padding         30
    bspc monitor eDP1 -d 1 2 3
    bspc monitor HDMI1 -d "4 [Monitor]"
# otherwise, i'm just running on the laptop
else
    bspc config top_padding        30
    bspc config bottom_padding     30
    bspc monitor eDP1 -d 1 2 3 4 5
fi

#---- settings ----#
#bspc config automatic_scheme longest_side
bspc config border_width        5
bspc config window_gap          15
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config click_to_focus      true

#---- colors ----#
bspc config focused_border_color \#ff6565
bspc config normal_border_color \#22313c

#---- rules ----#

#---- autostart ----#
(sleep 1 && nitrogen --restore) &
sxhkd &
xrdb ~/.Xresources &
compton &
(sleep 3 && polybar -c ~/.config/polybar/config.ini bottom) &
(sleep 3 && polybar -c ~/.config/polybar/config.ini top) &
nm-applet &
# helps window rendering in some java apps
wmname LG3D
