#! /bin/sh

bspc config -m HDMI1 top_padding        30
bspc config -m eDP1 top_padding         10

#---- monitors ----#
bspc monitor eDP1 -d I II
bspc monitor HDMI1 -d III IV


#---- rules ----#

#---- autostart ----#
(sleep 3 && ~/git-repos/polybar/build/bin/polybar example) &
